# Generated by Django 3.2.9 on 2021-11-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20211112_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='due',
            new_name='deadline',
        ),
    ]
